### ISSUE TITLE
Make pyproject.toml detect dependencies based on the platform

### ISSUE THREAD

**Issue by ByronHsu** [linkedin/Liger-Kernel#451]
### 🚀 The feature, motivation and pitch

The current pyproject.toml marks AMD dep as an optional, which is not ideal. We want the installation to auto detect the platform and decide which dependencies to use. Below is the example from claude, you can build on top:

```python
# build_helpers.py

import subprocess
import torch

def get_platform_dependencies():
    """Determine the appropriate dependencies based on detected hardware."""
    base_dependencies = [
        "torch>=2.1.2",
        "triton>=2.3.1",
    ]
    
    if torch.cuda.is_available():
        # CUDA-specific dependencies
        return base_dependencies
    
    # Check for ROCm/AMD
    try:
        result = subprocess.run(['rocm-smi'], capture_output=True, text=True)
        if result.returncode == 0:
            return [
                "torch>=2.6.0.dev",
                "setuptools-scm>=8",
                "torchvision>=0.20.0.dev",
                "triton>=3.0.0",
            ]
    except FileNotFoundError:
        pass
        
    return base_dependencies

def get_optional_dependencies():
    """Get optional dependency groups."""
    return {
        "transformers": [
            "transformers~=4.0"
        ],
        "dev": [
            "transformers>=4.44.2",
            "trl>=0.11.0",
            "matplotlib>=3.7.2",
            "flake8>=4.0.1.1",
            "black>=24.4.2",
            "isort>=5.13.2",
            "pytest>=7.1.2",
            "pytest-xdist",
            "pytest-rerunfailures",
            "datasets>=2.19.2",
            "torchvision>=0.16.2",
            "seaborn",
        ]
    }
```

```toml
[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "liger_kernel"
version = "0.4.2"
description = "Efficient Triton kernels for LLM Training"
urls = { "Homepage" = "https://github.com/linkedin/Liger-Kernel" }
readme = { file = "README.md", content-type = "text/markdown" }
license = { file = "LICENSE" }
dynamic = ["dependencies"]

[tool.setuptools.dynamic]
dependencies = {attr = "build_helpers.get_platform_dependencies"}
optional-dependencies = {attr = "build_helpers.get_optional_dependencies"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["liger_kernel", "liger_kernel.*"]

[tool.pytest.ini_options]
pythonpath = [
  "src",
  "."
]
asyncio_mode = "auto"
log_cli = true
log_cli_level = "INFO"
```
